version: '3'

services:
  mongo:
    image: mongo:4.4.3
    ports:
      - "27017:27017"
    networks:
      - socialmedia-network

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - socialmedia-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern-app
      - PORT=5000

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - socialmedia-network

networks:
  socialmedia-network:
    driver: bridge
