version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - mern-net
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: ./backend
    container_name: backend
    networks:
      - mern-net
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern-app

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - mern-net
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  mern-net:
    driver: bridge
